---
services:
  soju:
    container_name: soju
    build:
      context: .
      args:
        SOJU_VERSION: v0.10.1
    expose:
      - 6697
    volumes:
      - data_soju:/var/lib/soju
      - data_etc:/etc/soju


volumes:
  data_soju:
  data_etc:
