---
services:
  soju:
    container_name: soju
    build:
      context: .
      args:
        SOJU_VERSION: v0.10.1
    expose:
      - 6697
    volumes:
      - ../code/data/soju:/var/lib/soju
      - ../code/data/etc:/etc/soju
